from pydantic import BaseModel, Field


class ScoreBreakdown(BaseModel):
    """
    Individual scoring components used by the ranking engine.
    """

    deterministic_score: float = Field(
        ...,
        ge=0,
        le=100,
    )

    semantic_score: float = Field(
        ...,
        ge=0,
        le=100,
    )

    llm_score: float = Field(
        ...,
        ge=0,
        le=100,
    )

    final_score: float = Field(
        ...,
        ge=0,
        le=100,
    )


class LLMRankingEvaluation(BaseModel):
    """
    Structured evaluation generated by the LLM.
    """

    overall_score: float = Field(
        ...,
        ge=0,
        le=100,
    )

    skill_fit: float = Field(
        ...,
        ge=0,
        le=100,
    )

    experience_fit: float = Field(
        ...,
        ge=0,
        le=100,
    )

    responsibility_fit: float = Field(
        ...,
        ge=0,
        le=100,
    )

    project_fit: float = Field(
        ...,
        ge=0,
        le=100,
    )

    strengths: list[str] = Field(
        default_factory=list,
    )

    gaps: list[str] = Field(
        default_factory=list,
    )

    recommendation: str = Field(
        ...,
        min_length=1,
    )

    reasoning: str = Field(
        ...,
        min_length=1,
    )


class CandidateRanking(BaseModel):
    """
    Final ranking result for a single candidate.
    """

    rank: int = Field(
        ...,
        ge=1,
    )

    candidate_id: str

    candidate_name: str

    scores: ScoreBreakdown

    matched_required_skills: list[str] = Field(
        default_factory=list,
    )

    missing_required_skills: list[str] = Field(
        default_factory=list,
    )

    matched_preferred_skills: list[str] = Field(
        default_factory=list,
    )

    llm_evaluation: LLMRankingEvaluation | None = None

    strengths: list[str] = Field(
        default_factory=list,
    )

    gaps: list[str] = Field(
        default_factory=list,
    )

    recommendation: str

    explanation: str


class RankingResponse(BaseModel):
    """
    Complete ranking response returned by the API.
    """

    job_id: str

    total_candidates: int = Field(
        ...,
        ge=0,
    )

    rankings: list[CandidateRanking] = Field(
        default_factory=list,
    )
